#!/bin/bash

# Disable zswap
echo 0 > /sys/module/zswap/parameters/enabled

# Disable any active swaps
swapoff --all

# Load zram module
modprobe zram num_devices=1

# Set compression algorithm
echo zstd > /sys/block/zram0/comp_algorithm

# Set disk size
echo 8G > /sys/block/zram0/disksize

# Activate zram0
mkswap --label zram0 /dev/zram0
swapon --priority 32767 /dev/zram0
