---
- name: Determine the correct LUKS partition path
  set_fact:
    luks_partition: "{{ disk }}{{ 'p2' if 'nvme' in disk else '2' }}"

- name: Encrypt the partition using LUKS1
  command: cryptsetup --type luks1 -v -y luksFormat "{{ luks_partition }}"



- name: Display encryption status
  debug:
    msg: "Encryption successful for {{ luks_partition }}"
