---
- name: Encrypt the partition using LUKS1 with password prompt
  expect:
    command: cryptsetup --type luks1 -v -y luksFormat "{{ luks_partition }}"
    responses:
      "Enter passphrase for {{ luks_partition }}:": "your_password_here"
      "Verify passphrase:": "your_password_here"


- name: Display encryption status
  debug:
    msg: "Encryption successful for {{ luks_partition }}"
