---
- name: Open the encrypted partition
  command: cryptsetup open "{{ luks_partition }}" cryptdev

- name: Format the ESP partition with vfat
  command: mkfs.vfat -F32 -n ESP "{{ disk }}{{ 'p1' if 'nvme' in disk else '1' }}"

- name: Format the Linux root partition with btrfs
  command: mkfs.btrfs -L archlinux /dev/mapper/cryptdev

- name: Mount the root device
  mount:
    src: /dev/mapper/cryptdev
    path: /mnt
    fstype: btrfs
