---
- name: Verify if system is booted via UEFI
  stat:
    path: /sys/firmware/efi/efivars
  register: efi_check

- name: Fail if system is not booted via UEFI
  fail:
    msg: "System is not booted via UEFI. Please reboot in UEFI mode."
  when: not efi_check.stat.exists
