---
- name: Create pipx install directory
  file:
    path: /opt/pipx
    state: directory

- name: Configure pipx environment variables
  lineinfile:
    path: /etc/environment
    create: yes
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  loop:
    - regexp: '^PIPX_BIN_DIR='
      line: 'PIPX_BIN_DIR=/usr/local/bin'
    - regexp: '^PIPX_HOME='
      line: 'PIPX_HOME=/opt/pipx'

- name: Install ansible with additional dependencies
  community.general.pipx:
    name: ansible
    install_deps: yes
    state: install
    system_site_packages: yes
    inject_packages:
      - pywinrm
      - requests-credssp
      - dnspython
      - pyvmomi
      - pexpect
