---
- name: Display storage devices
  command: lsblk -f
  register: lsblk_output

- name: Prompt user to enter the disk identifier (e.g., /dev/sda or /dev/nvme0n1)
  pause:
    prompt: "Enter the disk identifier where Arch Linux will be installed: "
  register: disk_input

- name: Set the disk variable
  set_fact:
    disk: "{{ disk_input.user_input }}"

- name: Wipe the old partition layout
  command: "wipefs -af {{ disk }}"

- name: Clear the partition table
  command: "sgdisk --zap-all --clear {{ disk }}"

- name: Reload partition table
  command: "partprobe {{ disk }}"
